fix bugs in tklbam-init UI + refactor registry.update_profile
Desired behavior::

    # not initialized
    init
        should ask for APIKEY

    init --force
        should ask for APIKEY

    init --force-profile=core
        should ask for APIKEY and force profile to core

    # already initialized
    init
        error: already initialized

    init --force
        should ask for APIKEY if not provided

    init --force-profile=core
        should force update to profile